### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by Diagonet** [kai-dg/ffxiv-crafter-gather-automation#11]
Just following the instructions I already get an error from using cmd.bat (installing psutil) changing the required versio to 5.8.0 fixes that but still can't seem to get it to work. Not really experienced with python so sorry if I'm making a newbie mistake

**Comment by kokopi-dev** [comment]
sorry, missed this issue. i am in the middle of renewing. please look forward to it

**Comment by kokopi-dev** [comment]
check out the new readme for instructions on how to setup. it should be more automated to get things running. open a new issue if you still cant get it to work with the errors and details.
